---
resources:
  - name: concourse-tutorial
    type: git
    check_every: 30m
    source:
      uri: https://github.com/vinothsundararajan/concourse-lab.git
      branch: main
jobs:
  - name: maven-build-project
    public: true
    plan:
      - get: concourse-tutorial
      - task: pull-mvn-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: maven
              tag: latest
          inputs:
            - name: concourse-tutorial
          outputs:
            - name: concourse-app-output
          run:
            path: concourse-tutorial/ci/mvn.sh
            args: ["vinothsundararajan"]
###
#on_success:
#  do:
#  - put: maven-examples
#    params:
#      path: maven-examples
#      status: success
#on_failure:
#  do:
#  - put: maven-examples
#    params:
#      path: maven-examples
#      status: failure
####